[app]
title = Maker Lens
package.name = makerlens
package.domain = org.imt
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
requirements = python3,kivy
orientation = portrait
android.api = 33
android.minapi = 21
android.archs = arm64-v8a

