{
    "titre": "Laptop Cooling Stand",
    "main_image_url": "https://content.instructables.com/FUR/G4X1/LTIO2PD1/FURG4X1LTIO2PD1.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
    "main_image_caption": "",
    "difficulte": "",
    "duree": "",
    "cout": "",
    "source_link": "https://www.instructables.com/Laptop-Cooling-Stand/",
    "intro": "Ever had to shut your computer off because you're doing something resource-intensive during a trip? What about a gaming hobby? This is the solution to all your heat-related problems; Introducing... The Ultimate... Laptop Cooling Stand! NOTE: Steps8&9 are only if your printer can't fit the fully made stand. At step 7, check if you need to proceed.",
    "intro_items": [
        "Ever had to shut your computer off because you're doing something resource-intensive during a trip? What about a gaming hobby? This is the solution to all your heat-related problems; Introducing... The Ultimate... Laptop Cooling Stand!",
        "NOTE: Steps8&9 are only if your printer can't fit the fully made stand. At step 7, check if you need to proceed."
    ],
    "materiaux": [
        "Supplies<ul><li>Fusion 360</li><li>3d Printer</li><li>Superglue</li></ul>"
    ],
    "outils": [],
    "etapes": [
        {
            "html": "<strong>1. Step 1: Init</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FAE/IHUF/LTIO2RHT/FAEIHUFLTIO2RHT.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Init' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Here, we make the initial sketch. Select the right (YZ) plane and click \"Create Sketch\". Next, copy the image above to make it and them filet it.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>2. Step 2: Elongate</strong><div class='step-images count-2'><figure><img src='https://content.instructables.com/F15/Y80M/LTIO2T5N/F15Y80MLTIO2T5N.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Elongate' loading='lazy'></figure><figure><img src='https://content.instructables.com/FJ4/3IIZ/LTIO2U90/FJ43IIZLTIO2U90.png?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Elongate' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Next, extrude your sketch. Extrude it 10 inches and make sure that your selections for the \"edit feature\" match the two images above. Then, click \"OK\".</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>3. Step 3: Loops</strong><div class='step-images count-2'><figure><img src='https://content.instructables.com/F32/P4IV/LTIO2V7J/F32P4IVLTIO2V7J.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Loops' loading='lazy'></figure><figure><img src='https://content.instructables.com/F83/GDIZ/LTIO2V96/F83GDIZLTIO2V96.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Loops' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Here, create a sketch on top of your stand. Make a center point circle 6.50 mm in diameter like shown above.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>4. Step 4: Holes</strong><div class='step-images count-2'><figure><img src='https://content.instructables.com/FYB/S2DJ/LTIO2W2A/FYBS2DJLTIO2W2A.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Holes' loading='lazy'></figure><figure><img src='https://content.instructables.com/FRJ/5K4S/LTIO2W41/FRJ5K4SLTIO2W41.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Holes' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Next, extrude the circle inwards, but instead of selecting \"join\" on the bottom, change it to \"cut\". Extrude it in -10 mm, as shown above.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>5. Step 5: Dizzy</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FIX/6I0U/LTSO5XQE/FIX6I0ULTSO5XQE.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Dizzy' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Okay, this might lag your computer a bit: select \"Rectangular Pattern\", change the top dropdown from \"objects\" to \"Features\", select our hole for \"Objects\" and two perpendicular edges for \"Axes\". For the longest axis:</li><li>For the shortest Axis:</li><li>!IMPORTANT!<ul><li>Compute Type = Adjust</li></ul></li><li>you may get a warning to change your compute type. IGNORE THIS!!!<ul><li>Quantity(text box) = 15;</li><li>Distance(text box) = 470.00 mm;</li><li>Direction(dropdown) = One Direction.</li><li>Quantity(text box) = 8;</li><li>Distance(text box) = 240.00 mm;</li><li>Direction(dropdown) = One Direction.</li></ul></li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>6. Step 6: Rim</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FSK/GLX3/LTSO5XVJ/FSKGLX3LTSO5XVJ.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Rim' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now, create a sketch and make a corner rectangle that lines the top of our stand.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>7. Step 7: RimMaker</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FMN/3C30/LTSO5Y2M/FMN3C30LTSO5Y2M.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='RimMaker' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now, we are going to extrude the rim. Select Thin Extrude for type and then select \"Sketch 3\". Then, change wall thickness to 1.00 mm and distance to 2 mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>8. Step 8: Slicer</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FAE/I3RE/LTSO5Y94/FAEI3RELTSO5Y94.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Slicer' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Finally, make a sketch on the top face of our stand and make a bunch of lines on the thing. The goal is to get a bunch of sections that we print seperately. I personally found this amount of cuts to work.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>9. Step 9: Cuts</strong><div class='step-images count-2'><figure><img src='https://content.instructables.com/F0G/UH6N/LTSO613U/F0GUH6NLTSO613U.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Cuts' loading='lazy'></figure><figure><img src='https://content.instructables.com/FTT/MX5V/LTSO6162/FTTMX5VLTSO6162.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Cuts' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now, use the Split Body feature and select the lines you made in Step 8 that are going in the same direction under \"Splitting Tools\". Select \"Body 1\" under \"Bodies to Split\". Select \"Okay\". Then repeat, this time selecting all of the bodies for \"Bodies to Split\" and the lines going the other way. Good job! You completed it!</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        }
    ],
    "remarques": "",
    "mentions_legales": []
}