{
    "titre": "OW! That's Hot! Cup Gripper",
    "main_image_url": "https://content.instructables.com/FXH/NCLL/LU2O9EZ3/FXHNCLLLU2O9EZ3.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
    "main_image_caption": "",
    "difficulte": "",
    "duree": "",
    "cout": "",
    "source_link": "https://www.instructables.com/OW-Thats-Hot-Cup-Gripper/",
    "intro": "I made the OW! That's Hot! Cup Gripper so when picking up hot liquids in a cup, you won’t burn yourself. When printing, the pin will be in PLA, the two arms will be in PLA, and the two grips will be in TPU",
    "intro_items": [
        "I made the OW! That's Hot! Cup Gripper so when picking up hot liquids in a cup, you won’t burn yourself. When printing, the pin will be in PLA, the two arms will be in PLA, and the two grips will be in TPU"
    ],
    "materiaux": [
        "Supplies<ul><li>Fusion 360, a computer, glue, and a 3d printer that can print PLA and TPU.</li></ul>"
    ],
    "outils": [],
    "etapes": [
        {
            "html": "<strong>1. Step 1: The Sketch</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FZE/J1IS/LU2O9F06/FZEJ1ISLU2O9F06.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='The Sketch' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>First, make an 80mm circle, then, you can either inset it by 7.5mm, or make another circle inside the first one that is 72.5mm. Next, add a 68.5mm line on the larger circle at a 60 degree angle, and a 70mm on the smaller circle at a 60 degree angle as shown in the picture. No add two lines connecting the two lines together on the top and bottom. Now add one more line half way down the big rectangle you just made like shown in the picture. Finally, add a line going across the two circles like shown at the bottom of the picture. Now you have completed the initial sketch.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>2. Step 2: Extrusion Part 1</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FG8/PTYR/LU2O9F0Y/FG8PTYRLU2O9F0Y.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion Part 1' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>First, we will extrude this half of the circle by 20mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>3. Step 3: Extrusion Part 2</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FOG/BBBY/LU2O9F4T/FOGBBBYLU2O9F4T.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion Part 2' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Next, extrude the first half of the handle up 10mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>4. Step 4: Extrusion Part 3</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FY6/03RZ/LU2O9F77/FY603RZLU2O9F77.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion Part 3' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now we need to cut the first part of the handle. You can do this by extruding into it by 5mm like shown in the picture. Next, we will extrude the second part up 20mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>5. Step 5: Extrusion Part 4/ New Sketch</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FVT/D90V/LU2O9FBI/FVTD90VLU2O9FBI.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion Part 4/ New Sketch' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now create a sketch on the thin part of the handle. Create a centered 5mm circle and then click finish sketch. Now extrude that circle down and cut a hole in the handle. Now click on the top plain of the handle and extrude up 30mm</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>6. Step 6: Extrusion Part 5</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/F4Y/8NFO/LU2O9FG7/F4Y8NFOLU2O9FG7.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion Part 5' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now extrude the bottom plain of the handle by 30mm. Now you can turn off your sketches.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>7. Step 7: Handle Sketch</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/F4R/3EPU/LU2O9FI5/F4R3EPULU2O9FI5.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Handle Sketch' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Create a sketch on the handle and create a centered rectangle that's dimensions are 25mm by 60mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>8. Step 8: Extrusion</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FWD/DGIN/LU2O9FO9/FWDDGINLU2O9FO9.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extrusion' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now extrude the rectangle so it cuts through the handle. Finally extrude the thin part down 5mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>9. Step 9: Filleting (optional, But Highly Recommended)</strong><div class='step-images count-2'><figure><img src='https://content.instructables.com/F33/BKG7/LU2O9FOP/F33BKG7LU2O9FOP.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Filleting (optional, But Highly Recommended)' loading='lazy'></figure><figure><img src='https://content.instructables.com/FJL/0IMW/LU2O9FK4/FJL0IMWLU2O9FK4.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Filleting (optional, But Highly Recommended)' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Make sure to select all edges except for the inside grip and the pin hole. Fillet them 1mm. Congratulations! You’ve finished the arm!</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>10. Step 10: Sketching the Grip</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FAB/VI6L/LU2O9FQR/FABVI6LLU2O9FQR.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Sketching the Grip' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>First, create a circle that is 72.5mm, and then another inside it that is 65mm. Now create a line that goes across the circle that is 12.8mm away from the center point. Use the picture as reference.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>11. Step 11: Extruding</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FIT/N26Y/LU2O9FWO/FITN26YLU2O9FWO.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Extruding' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Now extrude this up 15mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        },
        {
            "html": "<strong>12. Step 12: Sketching and Extruding the Pin</strong><div class='step-images count-1'><figure><img src='https://content.instructables.com/FVK/GA75/LU2O9G0Y/FVKGA75LU2O9G0Y.png?auto=webp&fit=bounds&frame=1&height=1024&width=1024auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75' alt='Sketching and Extruding the Pin' loading='lazy'></figure></div><p><strong>Étapes :</strong></p><ol><li>Create a 4.9mm circle… and that’s it! Now extrude it up 20mm.</li></ol>",
            "fichiers": [
                {
                    "nom": "",
                    "type": "",
                    "description": "",
                    "lien": ""
                }
            ]
        }
    ],
    "remarques": "",
    "mentions_legales": []
}