{
    "DIY-Repair-Fixing-a-Broken-Air-Conditioner-Louver": {
        "titre": [
            "DIY Repair: Fixing a Broken Air Conditioner Louver With 3D Printing"
        ],
        "image": [
            {
                "url": "https://content.instructables.com/FNM/PB1N/M4FM6ZWA/FNMPB1NM4FM6ZWA.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                "alt": "DIY Repair: Fixing a Broken Air Conditioner Louver With 3D Printing",
                "description": ""
            }
        ],
        "difficulté": [],
        "durée": [],
        "coût": [],
        "liens": [
            "https://www.instructables.com/DIY-Repair-Fixing-a-Broken-Air-Conditioner-Louver/"
        ],
        "introduction": [
            {
                "titre": "The motor shaft of my air conditioner's louver broke, leaving me unable to adjust the airflow. Even when turned off, the louver wouldn't close. After unsuccessful attempts with adhesives and plastic repair kits, I decided to create a replacement part using a 3D printer. This guide documents the process of designing and printing a custom part to repair a broken louver on a Hitachi RAS-AJ-25B air conditioner.",
                "sous_items": []
            }
        ],
        "mentions légales": [],
        "matériaux": [],
        "outils": [],
        "étapes": [
            {
                "numero": 1,
                "titre": "Step 1: Louver Preparation",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "To replace the broken section entirely with the 3D printed part, I removed the broken piece using a nipper and a cutter. I marked the center line with a marker to ensure accurate alignment of the new part. For a better fit, I smoothed the surface of the louver where the part would attach.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FK6/HL36/M4FM6ZVF/FK6HL36M4FM6ZVF.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Louver Preparation",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/F80/IQNH/M4FM6ZVK/F80IQNHM4FM6ZVK.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Louver Preparation",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 2,
                "titre": "Step 2: Modeling the Replacement Part",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "I used TINKERCAD to model the replacement part. Given its simple shape and hidden location, a more complex software like Fusion360 wasn't necessary. TINKERCAD is a great tool for creating simple parts like this one.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Modeling the Base",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Since the louver surface is curved, I used a hemisphere shape to create a rounded base. The dimensions were set to 0.3mm thick, 25mm long, and 10mm wide. A slight gap was acceptable as the part would be glued in place.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Modeling the Triangular and Cylindrical Parts",
                                "sous_etapes": []
                            },
                            {
                                "titre": "I created a 10mm diameter cylinder, positioned 10mm above the louver surface, and supported it with a triangular part. The base of the triangular part measured 25mm x 10mm.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Motor Shaft Hole",
                                "sous_etapes": []
                            },
                            {
                                "titre": "The Hitachi RAS-AJ-25B uses a 24BYJ48 motor with a shaft size of 5mm wide and 3mm high. I created a hole slightly larger at 5.4mm wide and 3.4mm high to allow for a snug fit.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Combining Parts and Exporting STL",
                                "sous_etapes": []
                            },
                            {
                                "titre": "I combined all the parts into a single model and exported it as an STL file.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FW3/FFHT/M4FM6ZWT/FW3FFHTM4FM6ZWT.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Modeling the Replacement Part",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FFG/W2YN/M4FM6ZX4/FFGW2YNM4FM6ZX4.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Modeling the Replacement Part",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FD8/JPG9/M4FM6ZXG/FD8JPG9M4FM6ZXG.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Modeling the Replacement Part",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/F2G/XSLB/M4FM6ZXT/F2GXSLBM4FM6ZXT.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Modeling the Replacement Part",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/F50/QRHB/M4FM6ZWJ/F50QRHBM4FM6ZWJ.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Modeling the Replacement Part",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 3,
                "titre": "Step 3: 3D Printing",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "I used a QIDI X-Maker 3D printer. After slicing the STL file using the included slicer software, I printed the part using white filament. The print took approximately 10 minutes.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "3D Print Settings",
                                "sous_etapes": []
                            },
                            {
                                "titre": "While the default slicer settings worked well, I made a few adjustments:",
                                "sous_etapes": []
                            },
                            {
                                "titre": "",
                                "sous_etapes": [
                                    "Layer height: 0.4mm (for faster print times)",
                                    "Wall line count: 4 (to strengthen the walls with a 20% infill density)",
                                    "Z seam alignment: User-specified (to avoid the seam being on the bonding surface)"
                                ]
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FQU/TLSY/M4FM6ZY7/FQUTLSYM4FM6ZY7.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "3D Printing",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FAT/MNGO/M4FM71DV/FATMNGOM4FM71DV.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "3D Printing",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 4,
                "titre": "Step 4: Gluing the Part",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "I sanded the surfaces of both the louver and the 3D printed part to ensure a good bond. The adhesive is applied liberally to both sides of the bond, and the parts are pressed together after waiting 5-6 minutes. The adhesive hardens in 1-2 hours and reaches full strength in 24-48 hours.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FBB/F9LN/M4FM6ZVV/FBBF9LNM4FM6ZVV.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Gluing the Part",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FOV/UVXU/M4FM6ZYM/FOVUVXUM4FM6ZYM.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Gluing the Part",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 5,
                "titre": "Step 5: Conclusion",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "The repair was successful, and the louver now opens and closes smoothly. I believe that this method can be adapted to repair broken louvers on other air conditioner models.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FGA/6WTV/M4FM700D/FGA6WTVM4FM700D.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Conclusion",
                                "description": ""
                            }
                        ]
                    }
                ]
            }
        ],
        "annexes": []
    }
}