{
    "Roof-Window-Handle-Extension": {
        "titre": [
            "Roof Window Handle Extension"
        ],
        "image": [
            {
                "url": "https://content.instructables.com/FDH/JBE1/LG54QABZ/FDHJBE1LG54QABZ.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                "alt": "Roof Window Handle Extension",
                "description": ""
            }
        ],
        "difficulté": [],
        "durée": [],
        "coût": [],
        "liens": [
            "https://www.instructables.com/Roof-Window-Handle-Extension/"
        ],
        "introduction": [
            {
                "titre": "A customized handle extender for the roof window that helps me and my family to open and close windows in a bathroom and bedroom that are too high to reach and are difficult to open. The full guide is here.",
                "sous_items": []
            },
            {
                "titre": "Disclaimer. The object described in this guide is only an idea with an example STL file. The design is in testing and we won’t bear any responsibility for any accidental damage to the property if such occurs.",
                "sous_items": []
            }
        ],
        "mentions légales": [],
        "matériaux": [
            {
                "titre": "Supplies",
                "sous_items": [
                    "Filament - preferably stronger filaments such as PETG, and ABS, but also works with PLA if to follow the instructions.",
                    "M3 X40MM Bolts and Nuts. I used spare nuts from my previous Prusa MK2 3D printer. Amazon’s equivalent: of the bolts and nuts.",
                    "The Idea STL File: Cults3D or Printables."
                ]
            }
        ],
        "outils": [],
        "étapes": [
            {
                "numero": 1,
                "titre": "Step 1: Design",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "Handle was designed in Blender, nothing special. As usual, it all started with the cube which got expanded, sides and faces extruded into a lever-looking object. The top part was measured to fit the original window handle and the rest of the object was stretched to fit the Snapmaker A350T build platform diagonally. The final object is 380mm (15 inches) long.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FET/SI88/LG54QAC4/FETSI88LG54QAC4.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Design",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FET/SI88/LG54QAC4/FETSI88LG54QAC4.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Design",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 2,
                "titre": "Step 2: Slice",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "FDM 3D printing has some weaknesses that should be addressed when slicing an object that will have to resist certain forces. Our extension handle should be printed horizontally only with many perimeter shells.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Excessive perimeter shells (wall line count) and high percentage infill add to the object weight and printing time. When I was tuning the slicing settings, I focused on the area where M3 40mm screw and M3n locking nut will sit. To make sure the plastic will be consistent there to melt properly and withstand certain forces.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/FQ7/PD5D/LG54QB3H/FQ7PD5DLG54QB3H.png?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Slice",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FQ7/PD5D/LG54QB3H/FQ7PD5DLG54QB3H.png?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Slice",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 3,
                "titre": "Step 3: Print",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "As I mentioned before, the roof window extension handle was scaled to fit the print bed. Initially, it was the Snapmaker A350T 3D printer that the object had to fit. Snapmaker with the enclosed chamber can be good for printing such items in materials like ABS or Carbon Fibre-type filaments, for example. The controlled environment in the enclosed chamber helps against warping.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "The second printer of choice was Elegoo Neptune 3 Plus. Luckily, the same STL, without scaling a model, fit the print bed diagonally.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "On large print beds like on Elegoo Neptune 3 Max (420 x 420 x 500mm), Anycubic Kobra Max (400 x 400 x 450mm) such a tool could be made even longer, approximately up to 500mm (19.6 inches) long.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "The file can be adjusted to make it work on smaller printers just for the sake of the handle. Such a handle may be more comfortable to use.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": [
                            {
                                "url": "https://content.instructables.com/F4D/CC1Q/LG54QAC2/F4DCC1QLG54QAC2.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Print",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FRM/PZLU/LG54QB68/FRMPZLULG54QB68.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Print",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/F4D/CC1Q/LG54QAC2/F4DCC1QLG54QAC2.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Print",
                                "description": ""
                            },
                            {
                                "url": "https://content.instructables.com/FRM/PZLU/LG54QB68/FRMPZLULG54QB68.jpg?auto=webp&fit=bounds&frame=1auto=webp&frame=1&height=300&auto=webp&fit=bounds&width=600&height=450&quality=75",
                                "alt": "Print",
                                "description": ""
                            }
                        ]
                    }
                ]
            },
            {
                "numero": 4,
                "titre": "Step 4: Assembly",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "== DO NOT OVERTIGHT ==",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Before going further, there is one thing that is important to mention in any case. Maintain your windows by applying some lubricant solution to the hinges once in a while.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "The assembly is straightforward. I would recommend putting the nut in place before attaching the extension to the handle as it will be trickier to do afterward.",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": []
                    }
                ]
            },
            {
                "numero": 5,
                "titre": "Step 5: Conclusion",
                "solutions": [
                    {
                        "objectif": "",
                        "materiaux_outils": [],
                        "etapes": [
                            {
                                "titre": "This is an object that I use on a daily basis. I am very proud of this model and the idea, and that I had a chance to bring my design and 3D printing skills to something useful at home. In the comments below, please let me know if there is a possibility to improve such a model.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Files on Cults and Printables.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "According to our 3D print cost calculator, this 3D print job costs $20.57 if printed in Timberfill and $8.90 in other inexpensive and less fancy materials.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Was the model/idea helpful? Buy me a coffee on Ko-Fi.",
                                "sous_etapes": []
                            },
                            {
                                "titre": "Sharing or selling my digital files is not permitted. These remain my intellectual property. To obtain permission to sell physical prints of any of my designs, please subscribe to the commercial tier on Ko-Fi",
                                "sous_etapes": []
                            }
                        ],
                        "remarques": [],
                        "fichiers": [
                            {
                                "nom": "",
                                "type": "",
                                "description": "",
                                "lien": ""
                            }
                        ],
                        "images": []
                    }
                ]
            }
        ],
        "annexes": []
    }
}